[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci --include=dev',
    'npm run build',
    'ls -la public/build'
]

[phases.build]
paths = ['/app/public/build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
